-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 16:45:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Call_Center
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Call_Center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Call_Center` DEFAULT CHARACTER SET utf8 ;
USE `Call_Center` ;

-- -----------------------------------------------------
-- Table `Call_Center`.`Estado_Casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Estado_Casos` (
  `idEstado_Casos` INT NOT NULL AUTO_INCREMENT,
  `EstadoCasos_Nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idEstado_Casos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`Estado_Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Estado_Agentes` (
  `idEstado_Agentes` INT NOT NULL AUTO_INCREMENT,
  `EstadoAgentes_Nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idEstado_Agentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`Puesto_Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Puesto_Agentes` (
  `idPuesto_Agentes` INT NOT NULL AUTO_INCREMENT,
  `PuestoAgentes_Nombre` VARCHAR(45) NOT NULL,
  `Salario` DECIMAL NOT NULL,
  PRIMARY KEY (`idPuesto_Agentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Agentes` (
  `idAgente` INT NOT NULL AUTO_INCREMENT,
  `Agente_Nombre` VARCHAR(45) NOT NULL,
  `Usuario_Red` VARCHAR(45) NOT NULL,
  `Extension` INT NOT NULL,
  `idEstado_Agente` INT NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `idPuesto_Agentes` INT NOT NULL,
  PRIMARY KEY (`idAgente`),
  UNIQUE INDEX `Extension_UNIQUE` (`Extension` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_Red_UNIQUE` (`Usuario_Red` ASC) VISIBLE,
  INDEX `Estado_Agentes_idx` (`idEstado_Agente` ASC) VISIBLE,
  INDEX `Puesto_Agentes_idx` (`idPuesto_Agentes` ASC) VISIBLE,
  CONSTRAINT `Estado_Agentes`
    FOREIGN KEY (`idEstado_Agente`)
    REFERENCES `Call_Center`.`Estado_Agentes` (`idEstado_Agentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Puesto_Agentes`
    FOREIGN KEY (`idPuesto_Agentes`)
    REFERENCES `Call_Center`.`Puesto_Agentes` (`idPuesto_Agentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`Tipo_Casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Tipo_Casos` (
  `idTipo_Casos` INT NOT NULL AUTO_INCREMENT,
  `TiposCasos_Nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipo_Casos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`Casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`Casos` (
  `idCodigo_Caso` INT NOT NULL AUTO_INCREMENT,
  `idTipo_Caso` INT NOT NULL,
  `Fecha_Creacion` DATE NOT NULL,
  `idEstado_Casos` INT NOT NULL,
  `Fecha_Cierre` DATE NOT NULL,
  `idAgente` INT NOT NULL,
  `Descripcion_Caso` TEXT(1000) NOT NULL,
  PRIMARY KEY (`idCodigo_Caso`),
  INDEX `Estado_Casos_idx` (`idEstado_Casos` ASC) VISIBLE,
  INDEX `Agentes_idx` (`idAgente` ASC) VISIBLE,
  INDEX `Tipo_Casos_idx` (`idTipo_Caso` ASC) VISIBLE,
  CONSTRAINT `Estado_Casos`
    FOREIGN KEY (`idEstado_Casos`)
    REFERENCES `Call_Center`.`Estado_Casos` (`idEstado_Casos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Agentes`
    FOREIGN KEY (`idAgente`)
    REFERENCES `Call_Center`.`Agentes` (`idAgente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tipo_Casos`
    FOREIGN KEY (`idTipo_Caso`)
    REFERENCES `Call_Center`.`Tipo_Casos` (`idTipo_Casos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Call_Center`.`SubCasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Call_Center`.`SubCasos` (
  `idSubCasos` INT NOT NULL AUTO_INCREMENT,
  `idEstado_Casos` INT NOT NULL,
  `Fecha_Completado` DATE NOT NULL,
  `Descripcion_SubCaso` TEXT(1000) NOT NULL,
  `idCodigo_Caso` INT NOT NULL,
  PRIMARY KEY (`idSubCasos`),
  INDEX `Estado_SubCasos_idx` (`idEstado_Casos` ASC) VISIBLE,
  INDEX `Codigo_Caso_idx` (`idCodigo_Caso` ASC) VISIBLE,
  CONSTRAINT `Estado_SubCasos`
    FOREIGN KEY (`idEstado_Casos`)
    REFERENCES `Call_Center`.`Estado_Casos` (`idEstado_Casos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Codigo_Caso`
    FOREIGN KEY (`idCodigo_Caso`)
    REFERENCES `Call_Center`.`Casos` (`idCodigo_Caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
